# Generated by Django 3.0.8 on 2021-01-15 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sczone', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
