# Generated by Django 3.0.8 on 2021-01-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210115_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='caption',
            new_name='cap',
        ),
    ]
