# Generated by Django 3.0.8 on 2021-01-15 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210115_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='cap',
        ),
    ]
