# Generated by Django 3.0.6 on 2021-01-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210115_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='capp',
            field=models.CharField(max_length=100),
        ),
    ]
